
# Run all munge
source("./munge/00-Data Formatting.R")
# load the functions
source("./lib/funcs.R")

# Start running the munge scripts

source("./munge/01-WDI.R")
source("./munge/02-exchange rate volatility.R")
source("./munge/05-debt-to-GDP ratio.R")
source("./munge/06-inflation.R")
source("./munge/07-corruption.R")
source("./munge/08-coefficient of human inequality.R")
source("./munge/09-inform.R")
source("./munge/10-political rights.R")
source("./munge/12-income inequality.R")
source("./munge/14-criminal networks.R")
source("./munge/15-vdem.R")
source("./munge/16-media freedom.R")
source("./munge/17-SIPRI milex.R")
source("./munge/18-dietary energy supply adequacy.R")
source("./munge/19-water stress.R")
source("./munge/20-women's participation in UNFCCC.R")
source("./munge/21-environmental displacement.R")
source("./munge/22-interpersonal trust.R")
source("./munge/23-forced displacement (by asylum country).R")
source("./munge/24-forced displacement (by country of origin).R")
source("./munge/25-digital society project.R")
source("./munge/26-ND GAIN.R")
source("./munge/27-non renewable resource crime.R")
source("./munge/28-social protection.R")
source("./munge/29-EPI.R")
source("./munge/30-world governance indicators.R")
source("./munge/31-renewable energy.R")
source("./munge/32-sigi.R")
source("./munge/33-women's employment in non-agricultural sectors.R")
source("./munge/34-tax revenue.R")
source("./munge/35-non-state, one-sided conflict.R")
source("./munge/36-battledeaths.R")
#source("./munge/999-data finishing.R")

